project:
  type: book

book:
  title: "Open Science Guide for Parkinson's Research"
  author:
    - name: "Matthew J. Kmiecik"
      email: "mattk@23andme.com"
      orcid: "0000-0001-5340-3872"
    - name: "Hirotaka Iwaki"
      email: "hirotaka@datatecnica.com"
      orcid: "0000-0002-8982-7885"
  date: today
  doi: "10.5281/zenodo.14984668"
  navbar:
    left: 
      - icon: github
        href: https://github.com/MJFF-ResearchCommunity/open-science-guide
  chapters:
    - index.qmd
    - principles.qmd
    - considerations.qmd
    - tools.qmd
    - examples.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo